### ISSUE TITLE
Error thrown in hooked function '' for hook 'ready'. combatStart is not defined

### ISSUE THREAD

**Issue by samgrieve** [ChasarooniZ/pf2e-usage-updater#12]
I haven't noticed any issues whilst using the mod but did notice it is throwing an error in console each time I load itno 

``Error: Error thrown in hooked function '' for hook 'ready'. combatStart is not defined
[Detected 1 package: pf2e-usage-updater(2.1.2)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:140:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)
Caused by: ReferenceError: Error thrown in hooked function '' for hook 'ready'. combatStart is not defined
[Detected 1 package: pf2e-usage-updater(2.1.2)]
    at Object.fn (module.js:19:27)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)
onError	@	foundry.js:655
🎁call_wrapped	@	libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper	@	listeners.js:140
🎁Hooks.onError#0	@	libWrapper-wrapper.js:187
#call	@	foundry.js:636
callAll	@	foundry.js:589
setupGame	@	foundry.js:9098``

**Comment by ChasarooniZ** [comment]
Huh weird okay

**Comment by ChasarooniZ** [comment]
Ah I forgot to imporr
